-- liquibase formatted sql

-- changeset danila:1
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset danila:2
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

